/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VerificationRole;

import Business.Enterprise.Enterprise;
import Business.Organization.VerificationOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class VerificationWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private VerificationOrganization organization;
    private Enterprise enterprise;
    
    /**
     * Creates new form VerificationWorkeAreaJPanel
     */
    public VerificationWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, VerificationOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        jLabelEmpName.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewPolicyWR = new javax.swing.JButton();
        btnViewNewPolicy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmpName = new javax.swing.JLabel();
        btnPIIDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClaimWR = new javax.swing.JButton();

        btnNewPolicyWR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNewPolicyWR.setText("New Policy Verification WorkRequest");
        btnNewPolicyWR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPolicyWRActionPerformed(evt);
            }
        });

        btnViewNewPolicy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewNewPolicy.setText("View Policy Brochure");
        btnViewNewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNewPolicyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name:");

        jLabelEmpName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnPIIDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPIIDetails.setText("View/Edit Personal Details");
        btnPIIDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIIDetailsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Dashboard");

        btnClaimWR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClaimWR.setText("Claim Verification WorkRequest");
        btnClaimWR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimWRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewPolicyWR)
                    .addComponent(btnViewNewPolicy)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(btnPIIDetails)
                    .addComponent(btnClaimWR))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPIIDetails)
                .addGap(18, 18, 18)
                .addComponent(btnNewPolicyWR)
                .addGap(18, 18, 18)
                .addComponent(btnClaimWR)
                .addGap(18, 18, 18)
                .addComponent(btnViewNewPolicy)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPolicyWRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPolicyWRActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("NewPolicyWorkQueueJPanel", new NewPolicyWorkQueueJPanel(userProcessContainer, account,organization , enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewPolicyWRActionPerformed

    private void btnViewNewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNewPolicyActionPerformed
        ViewPolicyBrochureJPanel viewPolicyBrochureJPanel = new ViewPolicyBrochureJPanel(userProcessContainer, enterprise, organization, account);
        userProcessContainer.add("ViewPolicyBrochureJPanel", viewPolicyBrochureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewNewPolicyActionPerformed

    private void btnPIIDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIIDetailsActionPerformed
        ViewEditEmpPIIDetailsJPanel viewEditEmpPIIDetailsJPanel = new ViewEditEmpPIIDetailsJPanel(userProcessContainer, account);
        userProcessContainer.add("ViewEditEmpPIIDetailsJPanel", viewEditEmpPIIDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPIIDetailsActionPerformed

    private void btnClaimWRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimWRActionPerformed
        ClaimVerificationWorkQueueJPanel cClaimVerificationWorkQueueJPanel = new ClaimVerificationWorkQueueJPanel(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("ClaimVerificationWorkQueueJPanel", cClaimVerificationWorkQueueJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnClaimWRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaimWR;
    private javax.swing.JButton btnNewPolicyWR;
    private javax.swing.JButton btnPIIDetails;
    private javax.swing.JButton btnViewNewPolicy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEmpName;
    // End of variables declaration//GEN-END:variables
}
