/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NewCustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.NewCustomerOrganization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class NewCustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private NewCustomerOrganization organization;
    private Enterprise enterprise;
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public NewCustomerWorkAreaJPanel(JPanel userProcessContainer, NewCustomerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuyNewPolicy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        btnBuyNewPolicy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuyNewPolicy.setText("Buy New Policy");
        btnBuyNewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNewPolicyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Welcome to Northeastern Insurance Firm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnBuyNewPolicy))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnBuyNewPolicy)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyNewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNewPolicyActionPerformed
        userProcessContainer.removeAll();
        OrganizationDirectory ecOrgD = enterprise.getOrganizationDirectory();
        PolicyBrochure policyBrochure = new PolicyBrochure(userProcessContainer,enterprise, ecOrgD);
        userProcessContainer.add("Policy Brochure",policyBrochure);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyNewPolicyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyNewPolicy;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
