/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExistingCustomerRole;

import Business.Customer.Customer;
import Business.Enterprise.Enterprise;
import Business.OrderItem.OrderItem;
import Business.Organization.Organization;
import Business.Organization.VerificationOrganization;
import Business.Policy.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestVerificationNewPolicy;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class BuyNewPolicyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Customer customer;
    private Product policy;
    private UserAccount account;
    /**
     * Creates new form BuyNewPolicyJPanel
     */
    public BuyNewPolicyJPanel(JPanel upc, Enterprise e, Customer c, Product p, UserAccount a) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        this.customer = c;
        this.policy = p;
        this.account = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtAutoNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Add Automobile no.");

        txtAutoNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Automobile No.");

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBack)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(txtAutoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnProceed)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutoNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProceed)
                    .addComponent(btnBack))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkIfAutoNoIsUnique(String autoNo){
        for(Customer c : enterprise.getCustomerDirectory().getCustomerlist()){
            for (OrderItem oi : c.getOrderCustomerList()) {
                if(oi.getAutomobileNo().equals(autoNo)){
                    return false;
                }
            }
        }
        return true;
    }
    
    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        try {
            String autoMobileNo = txtAutoNo.getText().trim();
            if(checkIfAutoNoIsUnique(autoMobileNo) == true){
                String status = "Verification Pending";
                
                if(!autoMobileNo.matches("^[A-Z]{2}[ -][0-9]{1,2}(?: [A-Z])?(?: [A-Z]*)? [0-9]{4}$")){
                    JOptionPane.showMessageDialog(null , "Format is incorrect", "Information", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                
                customer.addCustomerOrderItem(policy, autoMobileNo, status);
                
                Date requestDate = new Date();
        
                RequestVerificationNewPolicy request = new RequestVerificationNewPolicy();
                request.setMessage(status);
                request.setSender(account);
                request.setStatus("Sent");
                request.setPolicy(policy);
                request.setRequestDate(requestDate);
//                request.getType("RequestVerificationNewPolicy");

                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof VerificationOrganization){
                        org = organization;
                        break;
                    }
                }
                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    account.getWorkQueue().getWorkRequestList().add(request);
                }
                
                JOptionPane.showMessageDialog(null , "On verification, policy status will get updated.", "Information", JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(null , " You can check your policy status and other details from your dashboard.", "Information", JOptionPane.INFORMATION_MESSAGE);
                
                btnProceed.setEnabled(false);
            } else{
                JOptionPane.showMessageDialog(null , "Automobile already exists! Please verify the no.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null , "please add correct field values.", "Information", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAutoNo;
    // End of variables declaration//GEN-END:variables
}
