/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExistingCustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ExistingCustomerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class ExisitingCustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private ExistingCustomerOrganization organization;
    private Enterprise enterprise;
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public ExisitingCustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ExistingCustomerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        jLabelCustName.setText(account.getCustomer().getCustName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnViewPloicyDetails = new javax.swing.JButton();
        btnBuyNewPolicy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelCustName = new javax.swing.JLabel();
        btnPIIDetails = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Dashboard");

        btnViewPloicyDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewPloicyDetails.setText("View Existing Policy Details");
        btnViewPloicyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPloicyDetailsActionPerformed(evt);
            }
        });

        btnBuyNewPolicy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuyNewPolicy.setText("View Policy Brochure");
        btnBuyNewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNewPolicyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name:");

        jLabelCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnPIIDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPIIDetails.setText("View/Edit Personal Details");
        btnPIIDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIIDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPloicyDetails)
                    .addComponent(btnBuyNewPolicy)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(btnPIIDetails))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCustName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPIIDetails)
                .addGap(18, 18, 18)
                .addComponent(btnViewPloicyDetails)
                .addGap(18, 18, 18)
                .addComponent(btnBuyNewPolicy)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyNewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNewPolicyActionPerformed
        PolicyBrochureJPanel policyBrochureJPanel = new PolicyBrochureJPanel(userProcessContainer, enterprise, organization, account);
        userProcessContainer.add("PolicyBrochureJPanel", policyBrochureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyNewPolicyActionPerformed

    private void btnPIIDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIIDetailsActionPerformed
        ViewEditPIIDetailsJPanel viewEditPIIDetailsJPanel = new ViewEditPIIDetailsJPanel(userProcessContainer, account);
        userProcessContainer.add("ViewEditPIIDetailsJPanel", viewEditPIIDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPIIDetailsActionPerformed

    private void btnViewPloicyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPloicyDetailsActionPerformed
        PolicyHistoryJPanel policyHistoryJPanel = new PolicyHistoryJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("PolicyHistoryJPanel", policyHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPloicyDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyNewPolicy;
    private javax.swing.JButton btnPIIDetails;
    private javax.swing.JButton btnViewPloicyDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCustName;
    // End of variables declaration//GEN-END:variables
}
