/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExistingCustomerRole;

import Business.Enterprise.Enterprise;
import Business.OrderItem.OrderItem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PolicyHistoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    
    /**
     * Creates new form ViewPolicyDetailsJPanel
     */
    public PolicyHistoryJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
    }
    
    public void populateTable(){
        int rowCount = tblPolicyHistory.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblPolicyHistory.getModel();
        
        for (OrderItem oi : account.getCustomer().getOrderCustomerList()) {
            Object row[] = new Object[8];
            row[0] = oi;
            row[1] = oi.getAutomobileNo();
            row[2] = oi.getStatus();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicyHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnClaim = new javax.swing.JButton();
        btnPolicyPlanDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblPolicyHistory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblPolicyHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Policy Plan Name", "Automobile No.", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPolicyHistory);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Policy Brochure");

        btnClaim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClaim.setText("Claim");
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });

        btnPolicyPlanDetail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPolicyPlanDetail.setText("Policy Plan Detail");
        btnPolicyPlanDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyPlanDetailActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(103, 103, 103)
                        .addComponent(btnClaim)
                        .addGap(88, 88, 88)
                        .addComponent(btnPolicyPlanDetail))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClaim)
                    .addComponent(btnPolicyPlanDetail)
                    .addComponent(btnBack))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPolicyPlanDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyPlanDetailActionPerformed
        int row = tblPolicyHistory.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrderItem orderItem = (OrderItem) tblPolicyHistory.getValueAt(row,0);
        
        SpecificPolicyDetailsJPanel specificPolicyDetailsJPanel = new SpecificPolicyDetailsJPanel(userProcessContainer, account, orderItem);
        userProcessContainer.add("SpecificPolicyDetailsJPanel", specificPolicyDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPolicyPlanDetailActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        int row = tblPolicyHistory.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(account.getCustomer().getClaimCounter()==2){
            JOptionPane.showMessageDialog(null, "Maximum claim request has been reached", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrderItem orderItem = (OrderItem) tblPolicyHistory.getValueAt(row,0);
        
        ClaimJPanel claimJPanel = new ClaimJPanel(userProcessContainer, account, orderItem, enterprise);
        userProcessContainer.add("ClaimJPanel", claimJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnClaimActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClaim;
    private javax.swing.JButton btnPolicyPlanDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPolicyHistory;
    // End of variables declaration//GEN-END:variables
}
