/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole.edit;

import Business.Enterprise.Enterprise;
import Business.Organization.OrganizationDirectory;
import Business.Policy.Product;
import UserInterface.AdministrativeRole.ManagePolicyJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class EditPolicyJPanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDirectory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Product product;
    /**
     * Creates new form EditPolicyJPanel
     */
    public EditPolicyJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDir, Enterprise enterprise, Product product) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDir;
        this.enterprise = enterprise;
        this.product = product;
        
        txtBenefit.setText(product.getPlanBenefit());
        txtDescription.setText(product.getDescription());
        txtDriverInsured.setText(product.getDriverInsured());
        txtDuration.setText(product.getDuration());
        txtPolicyMaxCover.setText(product.getPolicyMaxCover());
        txtPolicyName.setText(product.getPolicyName());
        txtVehicleClass.setText(product.getVehicleClass());
        txtPolicyPrice.setText(String.valueOf(product.getPolicyPrice()));
        
        txtBenefit.setEditable(false);
        txtDescription.setEditable(false);
        txtDriverInsured.setEditable(false);
        txtDuration.setEditable(false);
        txtPolicyMaxCover.setEditable(false);
        txtPolicyName.setEditable(false);
        txtPolicyPrice.setEditable(false);
        txtVehicleClass.setEditable(false);
        
        
        btnSave.setEnabled(false);
        btnEditPolicy.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPolicyMaxCover = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEditPolicy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        txtBenefit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtPolicyPrice = new javax.swing.JTextField();
        txtVehicleClass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDriverInsured = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        txtPolicyMaxCover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Description");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Policy Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Policy Price");

        btnEditPolicy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditPolicy.setText("Edit Policy");
        btnEditPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPolicyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Vehicle Class");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Driver Insured");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Edit Policy");

        txtPolicyName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDuration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtBenefit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Duration");

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPolicyPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtVehicleClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Plan Benefit");

        txtDriverInsured.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Policy Max Cover");

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPolicyPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBenefit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDuration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPolicyMaxCover)
                                .addComponent(txtVehicleClass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDriverInsured, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPolicyName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(60, 60, 60)
                        .addComponent(btnSave)
                        .addGap(58, 58, 58)
                        .addComponent(btnEditPolicy)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriverInsured, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyMaxCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBenefit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(btnEditPolicy)
                    .addComponent(btnSave))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPolicyActionPerformed
        txtBenefit.setEditable(true);
        txtDescription.setEditable(true);
        txtDriverInsured.setEditable(true);
        txtDuration.setEditable(true);
        txtPolicyMaxCover.setEditable(true);
        txtPolicyName.setEditable(true);
        txtPolicyPrice.setEditable(true);
        txtVehicleClass.setEditable(true);
        
        btnSave.setEnabled(true);
        btnEditPolicy.setEnabled(false);
        
    }//GEN-LAST:event_btnEditPolicyActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManagePolicyJPanel mpjp = (ManagePolicyJPanel) c;
        mpjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        try {
            String policyName = txtPolicyName.getText().trim();
            String description = txtDescription.getText().trim();
            String vehicleClass = txtVehicleClass.getText().trim();
            String driverInsured = txtDriverInsured.getText().trim();
            String policyMaxCover = txtPolicyMaxCover.getText().trim();
            String duration = txtDuration.getText().trim();
            String planBenefit = txtBenefit.getText().trim();
            int policyPrice = Integer.parseInt(txtPolicyPrice.getText().trim());

//            Product product = organizationDirectory.getProductCatalog().addProduct(policyName, description, vehicleClass, driverInsured, policyMaxCover, duration, planBenefit, policyPrice);

            product.setPolicyName(policyName);
            product.setDescription(description);
            product.setVehicleClass(vehicleClass);
            product.setDriverInsured(driverInsured);
            product.setPolicyMaxCover(policyMaxCover);
            product.setPlanBenefit(planBenefit);
            product.setPolicyPrice(policyPrice);
            product.setDuration(duration);

            JOptionPane.showMessageDialog(null , "Policy Updated", "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null , "Please add all the fields in correct order.", "Information", JOptionPane.ERROR_MESSAGE);
        }
        txtBenefit.setEditable(false);
        txtDescription.setEditable(false);
        txtDriverInsured.setEditable(false);
        txtDuration.setEditable(false);
        txtPolicyMaxCover.setEditable(false);
        txtPolicyName.setEditable(false);
        txtPolicyPrice.setEditable(false);
        txtVehicleClass.setEditable(false);
        
        btnSave.setEnabled(false);
        btnEditPolicy.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnEditPolicy;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBenefit;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDriverInsured;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtPolicyMaxCover;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyPrice;
    private javax.swing.JTextField txtVehicleClass;
    // End of variables declaration//GEN-END:variables
}
